### ISSUE TITLE
great project

### ISSUE THREAD

**Issue by BEAST-Community** [AgustinPardo/phylogeography#1]
i like your research very much, could you please tell me how to plot pie on the map, thanks.

**Comment by AgustinPardo** [comment]
Are you Xingguang Li?

**Comment by liamxg** [comment]
@AgustinPardo yes.

**Comment by liamxg** [comment]
@AgustinPardo can you help me plot my data.

**Comment by AgustinPardo** [comment]
@liamxg Which data do you need to be plot?

**Comment by liamxg** [comment]
@AgustinPardo , I sent you before.

**Comment by AgustinPardo** [comment]
@liamxg Which one do you need to plot?

**Comment by liamxg** [comment]
@AgustinPardo I sent it to your email.

**Comment by liamxg** [comment]
@AgustinPardo  like this?
<img width="844" alt="image" src="https://user-images.githubusercontent.com/46078579/222719941-a790c255-1b70-48bf-94fe-3aa685db7fdd.png">

**Comment by AgustinPardo** [comment]
Let me try!
